### ISSUE TITLE
log in python

### ISSUE THREAD

**Issue by timpx** [ins-amu/cluster#2]
In a python code, the following
```python
print "foo"
```
will be appended in to the log file as said in the submitting command only when the job is completely executed.

Will the logging module in python help to have "live" logging ?
for instance: 
```python
import logging
logging.basicConfig(filename='oarfliles/log', level=logging.DEBUG)
logging.debug('foo')
```

**Comment by timpx** [comment]
indeed it works, we should add this to the demo

**Comment by maedoc** [comment]
Are you sure? If you run, say, 

```python
import time

for i in range(60):
    time.sleep(60)
    print i
```
and you `tail -f` the log file, you don't see anything until it's done? I think you do.

**Comment by timpx** [comment]
+1 for the flush, it indeed seems to me that data was written by packs, as well as for logging.
I'll try this out as soon as the cluster will stop being occupied by me.

**Comment by maedoc** [comment]
> I'll try this out as soon as the cluster will stop being occupied by me.

`RecursionException`
